package com.bms.identity.domain;

/**
 * @author 王涛
 * @date 2026-09-10
 * @description 定义平台受保护操作对应的功能权限标识，是角色授权规则与应用服务访问控制之间的统一契约。
 */


public enum Permission {
    VIEW_CURRENT_TASK,
    VIEW_ALL_TASKS,
    CREATE_TASK,
    FILL_OPINION,
    REPLY_OPINION,
    CONFIRM_OPINION,
    VIEW_OPINION,
    UPLOAD_PCB_SCHEMATIC_FILE,
    DOWNLOAD_PCB_SCHEMATIC_FILE,
    UPLOAD_PROCESS_FILE,
    DOWNLOAD_PROCESS_FILE,
    UPLOAD_STRUCTURE_FILE,
    DOWNLOAD_STRUCTURE_FILE,
    MANAGE_USER,
    VIEW_USER,
    ASSIGN_PCB_EXPERT,
    ASSIGN_PROCESS_EXPERT,
    ASSIGN_STRUCTURE_EXPERT,
    ASSIGN_PCB_MUTUAL_CHECK,
    ASSIGN_SCHEMATIC_HARDWARE_EXPERT,
    ASSIGN_SCHEMATIC_OTHER_EXPERT,
    ASSIGN_SCHEMATIC_MUTUAL_CHECK,
    MANAGE_MUTUAL_CHECK,
    VIEW_MUTUAL_CHECK_OPINION,
    FINISH_PCB_TASK,
    FINISH_SCHEMATIC_TASK
}
