<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import StatusTag from '@/components/StatusTag.vue'
import TaskFlow from '@/components/TaskFlow.vue'
import BoardPreview from '@/components/BoardPreview.vue'
import { reviewApi } from '@/api/review-api'
import { identity } from '@/stores/identity'
import type { Archive, CheckItem, Opinion, Reviewer, Task } from '@/api/types'

const route = useRoute()
const taskId = computed(() => Number(route.params.taskId))
const activeTab = ref<'overview' | 'opinions' | 'check-items' | 'reviewers' | 'files' | 'archive'>('overview')
const task = ref<Task>()
const opinions = ref<Opinion[]>([])
const checkItems = ref<CheckItem[]>([])
const archive = ref<Archive>()
const reviewers = ref<Reviewer[]>([])
const reviewerRole = ref('PCB_EXPERT')
const loading = ref(true)
const error = ref('')
const notice = ref('')
const opinionForm = reactive({ sourceType: 'EXPERT_REVIEW' as Opinion['sourceType'], content: '', fileVersionId: undefined as number | undefined })
const replyDrafts = reactive<Record<number, { replyType: 'ACCEPT' | 'REJECT'; reason: string; fileVersionId?: number }>>({})
const reviewerIds = ref('')
const fileInput = ref<HTMLInputElement>()
const fileKey = ref('')
const fileCategory = ref('PCB_SCHEMATIC')
const selectedFile = ref<File>()

const statusText = computed(() => task.value?.status === 'FINISHED' ? '归档已经冻结，所有内容只读。' : '当前详情根据后端任务状态实时加载。')
const mutualOpinions = computed(() => opinions.value.filter((item) => item.sourceType === 'MUTUAL_CHECK_ITEM'))

async function load(): Promise<void> {
  loading.value = true; error.value = ''; notice.value = ''
  try {
    const [taskData, opinionsData, checkItemsData] = await Promise.all([reviewApi.getTask(taskId.value), reviewApi.listOpinions(taskId.value), reviewApi.listCheckItems(taskId.value)])
    task.value = taskData; opinions.value = opinionsData; checkItems.value = checkItemsData
    if (taskData.status === 'FINISHED') archive.value = await reviewApi.getArchive(taskId.value)
    await loadReviewers()
  } catch (cause) { error.value = cause instanceof Error ? cause.message : '加载任务详情失败' } finally { loading.value = false }
}
async function loadReviewers(): Promise<void> { try { reviewers.value = await reviewApi.listReviewers(taskId.value, reviewerRole.value) } catch { reviewers.value = [] } }
watch(reviewerRole, loadReviewers)
onMounted(load)

function setNotice(value: string): void { notice.value = value; window.setTimeout(() => { if (notice.value === value) notice.value = '' }, 3500) }
async function raiseOpinion(): Promise<void> {
  if (!opinionForm.content.trim()) { setNotice('请填写具体评审意见。'); return }
  try { await reviewApi.raiseOpinion(taskId.value, { ...opinionForm, content: opinionForm.content.trim() }); opinionForm.content = ''; opinions.value = await reviewApi.listOpinions(taskId.value); setNotice('评审意见已提交。') } catch (cause) { setNotice(cause instanceof Error ? cause.message : '提交失败') }
}
function draft(opinion: Opinion): { replyType: 'ACCEPT' | 'REJECT'; reason: string; fileVersionId?: number } { return replyDrafts[opinion.id] ??= { replyType: 'ACCEPT', reason: '' } }
async function replyOpinion(opinion: Opinion): Promise<void> { try { await reviewApi.replyOpinion(opinion.id, draft(opinion)); opinions.value = await reviewApi.listOpinions(taskId.value); setNotice('设计者答复已提交，等待提出人确认。') } catch (cause) { setNotice(cause instanceof Error ? cause.message : '答复失败') } }
async function confirmOpinion(opinion: Opinion, passed: boolean): Promise<void> { try { await reviewApi.confirmOpinion(opinion.id, { passed }); opinions.value = await reviewApi.listOpinions(taskId.value); setNotice(passed ? '已确认通过。' : '已退回设计者重新答复。') } catch (cause) { setNotice(cause instanceof Error ? cause.message : '确认失败') } }
async function saveCheckItem(item: CheckItem): Promise<void> { try { const result = (document.getElementById(`check-result-${item.id}`) as HTMLSelectElement).value; const comment = (document.getElementById(`check-comment-${item.id}`) as HTMLInputElement).value; const linkedOpinionId = Number((document.getElementById(`check-opinion-${item.id}`) as HTMLSelectElement).value) || undefined; await reviewApi.submitCheckItem(taskId.value, item.id, { result, comment, linkedOpinionId, version: item.version }); checkItems.value = await reviewApi.listCheckItems(taskId.value); setNotice('检查项已保存。') } catch (cause) { setNotice(cause instanceof Error ? cause.message : '保存失败') } }
async function saveReviewers(reassign = false): Promise<void> { const ids = reviewerIds.value.split(',').map((value) => Number(value.trim())).filter((value) => value > 0); if (!ids.length) { setNotice('请输入至少一个评审人 ID。'); return } try { reviewers.value = await reviewApi.assignReviewers(taskId.value, reviewerRole.value, ids, reassign); setNotice(reassign ? '评审人员已改派。' : '评审人员已分配。') } catch (cause) { setNotice(cause instanceof Error ? cause.message : '分配失败') } }
function selectFile(event: Event): void { selectedFile.value = (event.target as HTMLInputElement).files?.[0] }
async function checksum(file: File): Promise<string> { const digest = await crypto.subtle.digest('SHA-256', await file.arrayBuffer()); return Array.from(new Uint8Array(digest)).map((value) => value.toString(16).padStart(2, '0')).join('') }
async function registerFile(): Promise<void> { if (!selectedFile.value || !fileKey.value.trim()) { setNotice('请选择文件并填写文件业务标识。'); return } try { const session = await reviewApi.createUploadSession(taskId.value, fileCategory.value); const saved = await reviewApi.registerFile(taskId.value, { uploadSessionId: session.uploadSessionId, category: fileCategory.value, businessFileKey: fileKey.value.trim(), fileName: selectedFile.value.name, fileSize: selectedFile.value.size, md5: await checksum(selectedFile.value) }); setNotice(`文件元数据已登记，版本 V${saved.versionNo}。`); selectedFile.value = undefined; fileKey.value = ''; if (fileInput.value) fileInput.value.value = '' } catch (cause) { setNotice(cause instanceof Error ? cause.message : '文件登记失败') } }
async function download(fileId: number): Promise<void> { try { const result = await reviewApi.requestDownload(fileId); window.open(result.downloadUrl, '_blank', 'noopener') } catch (cause) { setNotice(cause instanceof Error ? cause.message : '下载失败') } }
function format(value?: string): string { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '—' }
function statusForCheck(item: CheckItem): string { return item.result ?? 'PENDING' }
</script>

<template>
  <div v-if="loading" class="loading page-loading">正在加载任务详情…</div>
  <div v-else-if="error" class="api-error page-loading"><b>无法加载任务</b><span>{{ error }}</span><button class="btn primary" @click="load">重试</button></div>
  <template v-else-if="task">
    <div class="page-head detail-head"><div><div class="crumb">任务列表 / 任务详情</div><h1>{{ task.taskName }}</h1><p>{{ task.projectName }} · {{ task.reviewType === 'PCB' ? 'PCB 评审' : '原理图评审' }}</p></div><StatusTag :value="task.status" /></div>
    <section class="card task-summary"><div class="summary-grid"><div><span>设计名称</span><b>{{ task.designName }}</b></div><div><span>设计者</span><b>用户 #{{ task.designerId }}</b></div><div><span>PCB 类型</span><b>{{ task.pcbType || '—' }}</b></div><div><span>当前阶段</span><b><StatusTag :value="task.status" /></b></div></div><TaskFlow :status="task.status" :review-type="task.reviewType" /></section>
    <p v-if="notice" class="toast-message">{{ notice }}</p>
    <div class="detail-tabs"><button v-for="item in [['overview','概览'],['opinions','专家意见'],['check-items','互检检查项'],['reviewers','评审人员'],['files','阶段文件'],['archive','归档记录']] as const" :key="item[0]" :class="{ active: activeTab === item[0] }" @click="activeTab = item[0]">{{ item[1] }}</button></div>
    <section v-if="activeTab === 'overview'" class="detail-grid"><div class="card"><h2>任务概览</h2><div class="detail-list"><div><span>任务状态</span><StatusTag :value="task.status" /></div><div><span>评审类型</span><b>{{ task.reviewType }}</b></div><div><span>意见总数</span><b>{{ opinions.length }}</b></div><div><span>互检项数量</span><b>{{ checkItems.length }}</b></div></div></div><div class="card"><h2>流程提示</h2><p class="notice">{{ statusText }}</p><p v-if="task.status !== 'FINISHED'" class="muted">后端流程推进接口需要任务乐观锁版本号，但当前任务详情响应未返回该字段；为避免错误提交，前端不展示“推进流程”按钮。</p><p v-else class="success-text">任务已结束，已可在“归档记录”查看冻结的数据。</p></div></section>
    <section v-else-if="activeTab === 'opinions'" class="tab-panel"><BoardPreview :title="task.designName" :file-name="`${task.reviewType === 'PCB' ? 'PCB' : '原理图'} 评审画布`" /><div class="two-column"><div class="card"><div class="section-head"><div><h2>提交评审意见</h2><p>提交后由设计者答复，提出人确认。</p></div></div><label>意见来源<select v-model="opinionForm.sourceType"><option value="EXPERT_REVIEW">专家评审</option><option value="PROCESS_REVIEW">工艺评审</option><option value="STRUCTURE_REVIEW">结构评审</option><option value="MUTUAL_EXTRA">互检额外意见</option></select></label><label>具体评审意见<textarea v-model="opinionForm.content" rows="7" placeholder="请输入具体、可执行的评审意见" /></label><button class="btn primary" @click="raiseOpinion">提交意见</button></div><div class="card"><h2>意见统计</h2><div class="stat-stack"><div><span>待答复</span><b>{{ opinions.filter((item) => item.status === 'PENDING_REPLY').length }}</b></div><div><span>待确认</span><b>{{ opinions.filter((item) => item.status === 'PENDING_CONFIRMATION').length }}</b></div><div><span>确认通过</span><b>{{ opinions.filter((item) => item.status === 'CONFIRMED_PASS').length }}</b></div></div></div></div>
      <div class="opinion-list"><article v-for="opinion in opinions" :key="opinion.id" class="card opinion-card"><div class="section-head"><div><span class="source-label">{{ opinion.sourceType }}</span><StatusTag :value="opinion.status" /><h3>{{ opinion.content }}</h3><p>提出人：用户 #{{ opinion.raisedBy }} · 意见 ID：{{ opinion.id }}</p></div></div><div v-if="opinion.designerReplies.length" class="reply-history"><b>设计者答复</b><div v-for="reply in opinion.designerReplies" :key="reply.id">第 {{ reply.replyNo }} 轮 · {{ reply.replyType }} · {{ reply.reason || '未填写补充说明' }} <small>{{ format(reply.repliedAt) }}</small></div></div><div v-if="task.designerId === identity.userId && opinion.status === 'PENDING_REPLY'" class="inline-form"><select v-model="draft(opinion).replyType"><option value="ACCEPT">接受并修改</option><option value="REJECT">不接受</option></select><input v-model="draft(opinion).reason" placeholder="答复说明" /><button class="btn primary" @click="replyOpinion(opinion)">提交答复</button></div><div v-if="opinion.raisedBy === identity.userId && opinion.status === 'PENDING_CONFIRMATION'" class="action-row"><button class="btn primary" @click="confirmOpinion(opinion, true)">确认通过</button><button class="btn danger" @click="confirmOpinion(opinion, false)">不通过</button></div></article><div v-if="!opinions.length" class="card empty">暂无评审意见</div></div></section>
    <section v-else-if="activeTab === 'check-items'" class="card tab-panel"><div class="section-head"><div><h2>互检单</h2><p>不合格检查项需要关联同源的互检意见。</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>序号</th><th>类别编码</th><th>检查项</th><th>结果</th><th>说明</th><th>关联意见</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in checkItems" :key="item.id"><td>{{ item.sortNo }}</td><td>{{ item.parentItemKey || '—' }}</td><td><b>{{ item.itemName }}</b><small>{{ item.templateItemKey }}</small></td><td><select :id="`check-result-${item.id}`"><option value="PASS" :selected="item.result === 'PASS'">合格</option><option value="FAIL" :selected="item.result === 'FAIL'">不合格</option><option value="NOT_APPLICABLE" :selected="item.result === 'NOT_APPLICABLE'">不适用</option></select></td><td><input :id="`check-comment-${item.id}`" :value="item.comment" placeholder="填写说明" /></td><td><select :id="`check-opinion-${item.id}`"><option value="">不关联</option><option v-for="opinion in mutualOpinions.filter((value) => value.sourceItemId === item.id)" :key="opinion.id" :selected="item.linkedOpinionId === opinion.id" :value="opinion.id">#{{ opinion.id }} {{ opinion.content }}</option></select></td><td><StatusTag :value="statusForCheck(item)" /></td><td><button class="btn compact" @click="saveCheckItem(item)">保存</button></td></tr><tr v-if="!checkItems.length"><td colspan="8" class="empty">当前任务尚未生成互检检查项</td></tr></tbody></table></div></section>
    <section v-else-if="activeTab === 'reviewers'" class="tab-panel"><div class="card"><div class="section-head"><div><h2>评审人员</h2><p>同一角色可同时分配多人，全部完成后该角色才完成。</p></div></div><div class="inline-form"><select v-model="reviewerRole"><option value="PCB_EXPERT">PCB 专家</option><option value="PROCESS_EXPERT">工艺专家</option><option value="STRUCTURE_EXPERT">结构专家</option><option value="PCB_MUTUAL_CHECK">PCB 互检</option><option value="SCHEMATIC_HARDWARE_EXPERT">原理图硬件专家</option><option value="SCHEMATIC_OTHER_EXPERT">原理图其他专家</option><option value="SCHEMATIC_MUTUAL_CHECK">原理图互检</option></select><input v-model="reviewerIds" placeholder="评审人 ID，多个用逗号分隔" /><button class="btn primary" @click="saveReviewers(false)">分配</button><button class="btn" @click="saveReviewers(true)">改派</button></div></div><div class="card"><table class="data-table"><thead><tr><th>评审人</th><th>角色</th><th>处理状态</th></tr></thead><tbody><tr v-for="reviewer in reviewers" :key="reviewer.reviewerId"><td>用户 #{{ reviewer.reviewerId }}</td><td>{{ reviewer.reviewRole }}</td><td><StatusTag :value="reviewer.processStatus" /></td></tr><tr v-if="!reviewers.length"><td colspan="3" class="empty">该角色暂未分配人员或当前用户无查看权限</td></tr></tbody></table></div></section>
    <section v-else-if="activeTab === 'files'" class="tab-panel"><div class="card"><h2>登记阶段文件</h2><p class="notice">本地 Mock 环境仅登记元数据；请选择文件后前端计算 SHA-256 并调用已有上传会话、文件登记接口。</p><div class="inline-form file-form"><select v-model="fileCategory"><option value="PCB_SCHEMATIC">PCB / 原理图文件</option><option value="PROCESS">工艺文件</option><option value="STRUCTURE">结构文件</option></select><input v-model="fileKey" placeholder="文件业务标识，例如 MAIN_PCB" /><input ref="fileInput" type="file" @change="selectFile" /><button class="btn primary" @click="registerFile">登记文件</button></div></div><div class="card"><h2>已归档阶段文件</h2><p v-if="!archive" class="muted">任务结束后，该区域将展示每条文件业务链的最新版本。</p><table v-else class="data-table"><thead><tr><th>阶段</th><th>文件名</th><th>版本</th><th>上传人</th><th>上传时间</th><th>操作</th></tr></thead><tbody><tr v-for="file in archive.stageFiles" :key="file.fileId"><td>{{ file.stageName }}</td><td>{{ file.fileName }}</td><td>V{{ file.versionNo }}</td><td>{{ file.uploaderName }}</td><td>{{ format(file.uploadedAt) }}</td><td><button class="btn compact" @click="download(file.fileId)">下载</button></td></tr></tbody></table></div></section>
    <section v-else class="tab-panel"><div v-if="!archive" class="card unsupported"><div class="unsupported-icon">⌁</div><h2>任务尚未结束</h2><p>任务完成时，后端会冻结流转意见、阶段文件与邮件记录。</p></div><template v-else><div class="card"><div class="section-head"><div><h2>一、流转意见</h2><p>已包含专家意见和设计者答复。</p></div></div><table class="data-table"><thead><tr><th>时间</th><th>阶段</th><th>操作人</th><th>流转意见</th></tr></thead><tbody><tr v-for="item in archive.flowOpinions" :key="`${item.source}-${item.sourceId}`"><td>{{ format(item.occurredAt) }}</td><td>{{ item.stageName }}</td><td>{{ item.operatorName }}</td><td>{{ item.content }}<div v-if="item.designerReplies.length" class="reply-history"><b>设计者答复：</b><div v-for="reply in item.designerReplies" :key="reply.replyNo">第 {{ reply.replyNo }} 轮：{{ reply.replyType }} · {{ reply.content || '—' }}</div></div></td></tr></tbody></table></div><div class="card"><h2>二、阶段文件</h2><table class="data-table"><thead><tr><th>阶段</th><th>文件名</th><th>上传人</th><th>上传时间</th><th>操作</th></tr></thead><tbody><tr v-for="file in archive.stageFiles" :key="file.fileId"><td>{{ file.stageName }}</td><td>{{ file.fileName }}</td><td>{{ file.uploaderName }}</td><td>{{ format(file.uploadedAt) }}</td><td><button class="btn compact" @click="download(file.fileId)">下载</button></td></tr></tbody></table></div><div class="card"><h2>三、邮件记录</h2><table class="data-table"><thead><tr><th>发送时间</th><th>场景</th><th>收件人</th><th>状态</th></tr></thead><tbody><tr v-for="mail in archive.mailRecords" :key="`${mail.sentAt}-${mail.recipient}`"><td>{{ format(mail.sentAt) }}</td><td>{{ mail.scenario }}</td><td>{{ mail.recipient }}</td><td><StatusTag :value="mail.deliveryStatus" /></td></tr><tr v-if="!archive.mailRecords.length"><td colspan="4" class="empty">暂无邮件投递记录</td></tr></tbody></table></div></template></section>
  </template>
</template>
