<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { reviewApi } from '@/api/review-api'
import type { TemplateCategory } from '@/api/types'

type EditableItem = { id?: number; itemKey: string; itemName: string; sortNo: number; enabled: boolean; version?: number }
const fileInput = ref<HTMLInputElement>()
const importing = ref(false)
const saving = ref(false)
const loading = ref(true)
const error = ref('')
const message = ref('')
const reviewType = ref('PCB')
const categories = ref<TemplateCategory[]>([])
const createOpen = ref(true)
const editorOpen = ref(false)
const editingId = ref<number>()
const editor = reactive({ categoryKey: '', categoryName: '', sortNo: 0, enabled: true, version: 0, items: [] as EditableItem[] })
const enabledCategories = computed(() => categories.value.filter((item) => item.category.enabled))

function resetEditor(): void { editingId.value = undefined; Object.assign(editor, { categoryKey: '', categoryName: '', sortNo: categories.value.length, enabled: true, version: 0, items: [{ itemKey: '', itemName: '', sortNo: 0, enabled: true }] }) }
async function load(): Promise<void> { loading.value = true; error.value = ''; try { categories.value = await reviewApi.listTemplates(reviewType.value) } catch (cause) { error.value = cause instanceof Error ? cause.message : '加载互检模板失败' } finally { loading.value = false } }
function openCreate(): void { resetEditor(); createOpen.value = true; editorOpen.value = false }
function openEdit(category: TemplateCategory): void { editingId.value = category.category.id; Object.assign(editor, { categoryKey: category.category.itemKey, categoryName: category.category.itemName, sortNo: category.category.sortNo, enabled: category.category.enabled, version: category.category.version, items: category.items.map((item) => ({ id: item.id, itemKey: item.itemKey, itemName: item.itemName, sortNo: item.sortNo, enabled: item.enabled, version: item.version })) }); editorOpen.value = true }
function addItem(): void { editor.items.push({ itemKey: '', itemName: '', sortNo: editor.items.length, enabled: true }) }
function removeItem(index: number): void { if (editor.items.length > 1) editor.items.splice(index, 1) }
async function save(): Promise<void> { saving.value = true; error.value = ''; message.value = ''; try { const keySeed = `MANUAL-${Date.now()}`; const body = { reviewType: reviewType.value, categoryKey: editor.categoryKey.trim() || `${keySeed}-CATEGORY`, categoryName: editor.categoryName.trim(), sortNo: editor.sortNo, enabled: editor.enabled, version: editor.version, items: editor.items.map((item, index) => ({ ...item, itemKey: item.itemKey.trim() || `${keySeed}-ITEM-${index + 1}`, itemName: item.itemName.trim() })) }; if (editingId.value) await reviewApi.updateTemplate(editingId.value, body); else await reviewApi.createTemplate({ reviewType: body.reviewType, categoryKey: body.categoryKey, categoryName: body.categoryName, sortNo: body.sortNo, items: body.items.map(({ itemKey, itemName, sortNo, enabled }) => ({ itemKey, itemName, sortNo, enabled })) }); message.value = editingId.value ? '类别及检查项已更新。' : '互检类别已创建。'; editorOpen.value = false; createOpen.value = false; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : '保存失败，请填写类别和检查项名称。' } finally { saving.value = false } }
async function disable(category: TemplateCategory): Promise<void> { if (!window.confirm(`确认停用“${category.category.itemName}”及其检查项吗？已创建任务不会被删除。`)) return; try { await reviewApi.disableTemplate(category.category.id, category.category.version); message.value = '类别已停用。'; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : '停用失败' } }
async function importWorkbook(event: Event): Promise<void> { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; importing.value = true; error.value = ''; message.value = ''; try { const result = await reviewApi.importTemplate(file); message.value = `导入完成：共 ${result.totalRows} 行，新增 ${result.createdCount} 条，更新 ${result.updatedCount} 条。`; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : '导入失败' } finally { importing.value = false; if (fileInput.value) fileInput.value.value = '' } }
onMounted(async () => { resetEditor(); await load() })
</script>

<template>
  <div class="page-head template-head"><div><h1>互检单管理</h1></div><div class="action-row"><button v-if="!createOpen" class="btn primary" @click="openCreate">＋ 新增类别</button><button class="btn" :disabled="importing" @click="fileInput?.click()">{{ importing ? '导入中…' : '导入 Excel' }}</button><input ref="fileInput" class="hidden" type="file" accept=".xlsx" @change="importWorkbook" /></div></div>
  <form v-if="createOpen" class="card inline-create-card" @submit.prevent="save"><div class="section-head"><h2>新增类别</h2><button class="btn" type="button" @click="createOpen = false">取消</button></div><label>类别 *<input v-model="editor.categoryName" required placeholder="例如：高速信号" /></label><div class="section-head create-items-head"><label>检查项 *</label><button class="btn" type="button" @click="addItem">＋ 新增检查项</button></div><div v-for="(item, index) in editor.items" :key="index" class="inline-item-row"><input v-model="item.itemName" required placeholder="请输入检查项名称" /><button class="btn danger" type="button" :disabled="editor.items.length === 1" @click="removeItem(index)">删除</button></div><footer class="form-footer"><button class="btn primary" :disabled="saving" type="submit">{{ saving ? '保存中…' : '保存类别' }}</button></footer></form>
  <p v-if="message" class="success-text">{{ message }}</p><p v-if="error" class="form-error">{{ error }}</p>
  <section v-if="loading" class="card loading">正在加载互检模板…</section>
  <section v-else class="card template-root"><div class="section-head"><h2>互检单模板</h2><span class="tag">{{ enabledCategories.length }} 个类别</span></div><div class="template-list"><article v-for="group in categories" :key="group.category.id" class="template-group" :class="{ disabled: !group.category.enabled }"><header><div><span class="category-badge">类别</span><b>{{ group.category.itemName }}</b><small>{{ group.items.length }} 个检查项</small></div><div class="action-row"><button class="btn compact" @click="openEdit(group)">编辑类别</button><button v-if="group.category.enabled" class="btn compact danger" @click="disable(group)">删除</button></div></header><div v-for="(item, index) in group.items" :key="item.id" class="template-item"><span>{{ index + 1 }}</span><b>{{ item.itemName }}</b><em v-if="!item.enabled">已停用</em><button class="text-link" @click="openEdit(group)">编辑检查项</button></div><button class="btn compact add-item" @click="openEdit(group)">＋ 新增检查项</button></article><div v-if="!categories.length" class="empty">暂无模板类别，请新增类别或导入 Excel。</div></div></section>
  <section v-if="editorOpen" class="editor-backdrop" @click.self="editorOpen = false"><form class="card template-editor" @submit.prevent="save"><div class="section-head"><div><h2>{{ editingId ? '编辑互检类别' : '新增互检类别' }}</h2><p>类别与子检查项将在一次请求中保存。</p></div><button class="btn compact" type="button" @click="editorOpen = false">关闭</button></div><div class="form-grid editor-category"><label>类别编码<input v-model="editor.categoryKey" required placeholder="例如：PCB-ROUTING" /></label><label>类别名称<input v-model="editor.categoryName" required placeholder="例如：布局布线" /></label><label>排序号<input v-model.number="editor.sortNo" type="number" min="0" required /></label></div><div class="editor-items"><div class="section-head"><h2>检查项</h2><button class="btn compact" type="button" @click="addItem">＋ 新增检查项</button></div><div v-for="(item, index) in editor.items" :key="index" class="editor-item"><span>{{ index + 1 }}</span><input v-model="item.itemKey" required placeholder="检查项编码" /><input v-model="item.itemName" required placeholder="检查项名称" /><input v-model.number="item.sortNo" type="number" min="0" /><button class="btn compact danger" type="button" :disabled="editor.items.length === 1" @click="removeItem(index)">删除</button></div></div><footer class="form-footer"><button class="btn" type="button" @click="editorOpen = false">取消</button><button class="btn primary" :disabled="saving" type="submit">{{ saving ? '保存中…' : '保存' }}</button></footer></form></section>
</template>

<style scoped>
.template-head{align-items:center}.inline-create-card{margin-bottom:18px}.inline-create-card label{display:grid;gap:8px;font-weight:600;font-size:13px;color:#303648}.inline-create-card input{width:100%;border:1px solid #dce0eb;border-radius:7px;padding:11px;background:#fafbfe}.create-items-head{margin:20px 0 10px;align-items:center}.inline-item-row{display:grid;grid-template-columns:1fr auto;gap:10px;margin:10px 0}.template-root{padding:18px}.template-list{display:grid;gap:14px}.template-group{border:1px solid #e0e3ed;border-radius:10px;overflow:hidden}.template-group.disabled{opacity:.65}.template-group header{display:flex;justify-content:space-between;align-items:center;padding:16px 20px;background:#fbfbfe;border-bottom:1px solid #ececf2}.category-badge{display:inline-block;padding:4px 8px;margin-right:10px;border-radius:5px;background:#f0edff;color:#6558d4;font-size:12px}.template-group header b{font-size:16px}.template-group header small{margin-left:10px;color:#7c8192}.template-item{min-height:49px;display:grid;grid-template-columns:32px 1fr auto auto;align-items:center;gap:10px;padding:0 20px;border-bottom:1px solid #eeeef3;font-size:13px}.template-item>span{display:grid;place-items:center;width:27px;height:27px;border-radius:50%;background:#f3f4f8;color:#62677a;font-size:12px}.template-item em{font-style:normal;color:#ba7b27;font-size:12px}.template-item button{border:0;background:transparent;font-size:12px}.add-item{margin:12px 20px}.editor-backdrop{position:fixed;inset:0;z-index:30;display:grid;place-items:center;padding:20px;background:rgba(25,27,45,.36)}.template-editor{width:min(920px,100%);max-height:90vh;overflow:auto}.editor-category{grid-template-columns:1fr 1.5fr 120px}.editor-items{padding:13px;border:1px solid #e6e7ef;border-radius:8px}.editor-item{display:grid;grid-template-columns:28px 1fr 1.5fr 90px auto;gap:8px;align-items:center;margin-bottom:8px}.editor-item input{border:1px solid #dedfe8;border-radius:7px;padding:8px}.editor-item>span{color:#777c8d;text-align:center}@media(max-width:720px){.template-head,.template-group header{align-items:flex-start;flex-direction:column}.editor-category,.editor-item{grid-template-columns:1fr}.editor-item>span{display:none}}
</style>
